<a href="https://colab.research.google.com/github/alanwuha/ce7455-nlp/blob/master/data-structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5. Data Structures

This chapter describes some things you've learned about already in more detail, and adds some new things as well.

## 5.1. More on Lists

The list data type has some more methods. Here are all of the methods of list objects:

list.__append__(_x_): Add an item to the end of the list. Equivalent to `a[len(a):] = [x]`.

list.__extend__(_iterable_): Extend the list by appending all the items from the iterable. Equivalent to `a[len(a):] = iterable`.

list.__insert__(_i, x_): Insert an item at a given position. The first argument is the index of the element before which to insert, so `a.insert(0, x)` inserts at the front of the list, and `a.insert(len(a), x)` is equivalent to `a.append(x)`.

list.__remove__(_x_): Remove the first item from the list whose value is _x_. It is an error if there is no such item.

list.__pop__([_i_]): Remove the item at the given position in the list, and return it. If no index is specified, `a.pop()` removes and returns the last item in the list. (The square brackets around the _i_ in the method signature denote that the parameter is optional, not that you should type square brackets at that position. You will see this notation frequently in the Python Library Reference.)

list.__clear__(): Remove all items from the list. Equivalent to `del a[:]`.

list.__index__(x[, start [, end]]): Return zero-based in the list of the first item whose value is _x_. Raises a [ValueError](#) if there is no such item. The optional arguments _start_ and _end_ are interpreted as in the slice notation and are used to limit the search to a particular subsequence of the list. The returned index is computed relative to the beginning of the full sequence rather than the _start_ argument.

list.__count__(x): Return the number of times _x_ appears in the list.

list.__sort__(_key=None, reverse=False_): Sort the items of the list in place (the arguments can be used for sort customization, see [sorted()](#) for their explanation).

list.__reverse__(): Reverse the elements of the list in place.

list.__copy__(): Return a shallow copy of the list. Equivalent to `a[:]`.

An example that uses most of the list methods:

In [2]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(fruits.count('apple'))
print(fruits.count('tangerine'))
print(fruits.index('banana'))
print(fruits.index('banana', 4))  # Find next banana starting a position 4
fruits.reverse()
print(fruits)
fruits.append('grape')
print(fruits)
fruits.sort()
print(fruits)
print(fruits.pop())

2
0
3
6
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']
['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']
pear


You might have noticed that methods like `insert`, `remove`, or `sort` that only modify the list have no return value printed - they return the default `None`. [[1]](#) This is a design principle for all mutable data structures in Python.

[[1]](#) Other languages may return the mutated object, which allows method chaining, such as `d->insert("a")->remove("b")->sort();`.

## 5.1.3. List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

For example, assume we want to create a list of squares, like:

In [7]:
squares = list(map(lambda x: x**2, range(10)))
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [9]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### 5.3. Tuples and Sequences

We saw that lists and strings have many common properties, such as indexing and slicing operations. They are **two examples of _sequence_ data types** (see [Sequence Types -- list, tuple, range](#)). Since Python is an evolving language, other sequence data types may be added. There is also **another standard sequence data type: the _tuple_**.

A tuple consists of a __number of values separated by commas__, for instance:

In [19]:
t = 12345, 54321, 'hello!'
print(t[0])
print(t)

# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
print(u)

# Tuples are immutable:
# t[0] = 88888

# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
print(v)
print(v[0])

v[0][0] = 4
print(v)

12345
(12345, 54321, 'hello!')
((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))
([1, 2, 3], [3, 2, 1])
[1, 2, 3]
([4, 2, 3], [3, 2, 1])


As you see, on output tuples are always enclosed in parentheses, so that nested tuples are interpreted correctly; they may be input with or without surrounding parentheses, although often parentheses are necessary anyway (if the tuple is part of a larger expression). It is not possible to assign to the individual items of a tuple, however it is possible to create tuples which contain mutable objects, such as lists.

Though tuples may seem similar to lists, they are often used in different situations and for different purpose. Tuples are [immutable](#), and usually contain a heterogeneous sequence of elements that are accessed via unpacking (see later in this section) or indexing (or even by attribute in the case of [namedtuples](#)). Lists are [mutable](#), and their elements are usually homogeneous and are accessed by iterating over the list.

A special problem is the construction of tuples containing 0 or 1 items: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parenthese; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parenthese). Ugly, but effective. For example:

In [20]:
empty = ()
singleton = 'hello',  # <-- note trailing comma
print(len(empty))
print(len(singleton))
print(singleton)

0
1
('hello',)


In [25]:
lst = [i for i in range(10)]
tple = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
print(type(lst), type(tple))

<class 'list'> <class 'tuple'>


The statement `t = 12345, 54321, 'hello'!` is an example of __tuple packing__: the values `12345`, `54321`, and `'hello!'` are packed together in a tuple. The reverse operation is also possible:

In [27]:
x, y, z = t
print(x, y, z)

12345 54321 hello!


This is called, appropriately enough, _sequence unpacking_ and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.

## 5.4. Sets

Python also includes a data type for _sets_. A set is an __unordered collection__ with __no duplicate elements__. Basic uses include __membership testing__ and __eliminating duplicate entries__. Set objects also support __mathematical operations__ like union, intersection, difference, and symmetric difference.

Curly braces or the [set()](#) function can be used to create sets. Note: to create an empty set you have to use `set()`, not `{}`; the latter creates an empty dictionary, a data structure that we discuss in the next section.

Here is a brief demonstration:

In [34]:
# A set is an unordered collection with no duplicate elements
# Basic uses include membership testing and eliminating duplicate entries
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)
print('orange' in basket) # fast membership testing
print('crabgrass' in basket)

# Demonstrate set operations on unique letters from two words
a = set('abracadabra')
b = set('alacazam')
print(a)  # unique leeters in a
print(a - b)  # letters in a but not in b
print(a | b)  # letters in a or b or both
print(a & b)  # letters in both a and b
print(a ^ b)  # letters in a or b but not both

{'apple', 'pear', 'orange', 'banana'}
True
False
{'c', 'r', 'b', 'd', 'a'}
{'r', 'b', 'd'}
{'m', 'c', 'r', 'd', 'b', 'z', 'l', 'a'}
{'c', 'a'}
{'z', 'l', 'd', 'm', 'r', 'b'}


Similarly to [list comprehensions](#), set comprehensions are also supported:

In [35]:
a = { x for x in 'abracadabra' if x not in 'abc' }
a

{'d', 'r'}

### 5.5 Dictionaries

Another useful data type built into Python is the _dictionary_ (see [Mapping Types - dict](#)). Dictionaries are sometimes found in other languages as "associative memories" or "associative arrays". Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by _keys_, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can't use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like append() and extend().

It is best to think of a dictionary as an unordered set of _key: value_ pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: `{}`. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this also the way dictionaries are written on output.

The main operations on a dictionary are:
  1. storing a value with some key
  1. extracting the value given the key
  1. delete a key:value pair with `del`

If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing `list(d.keys())` on a dictionary returns a list of all the keys used in the dictionary, in arbitrary order (if you want it sorted, just use `sorted(d.keys())` instead). [[2]](#) To check whether a single key is in the dictionary, use the [in](#) keyword.

Here is a small example using a dictionary:

In [46]:
tel = { 'jack': 4098, 'sape': 4139 }
tel['guido'] = 4127
print(tel)

print(list(tel.keys()))
print(sorted(tel.keys()))
print(list(tel.values()))
print(sorted(tel.values()))

print(tel['jack'])
del tel['sape']
print(tel)

tel['irv'] = 4127
print(tel)

print('guido' in tel)
print('jack' not in tel)

{'jack': 4098, 'sape': 4139, 'guido': 4127}
['jack', 'sape', 'guido']
['guido', 'jack', 'sape']
[4098, 4139, 4127]
[4098, 4127, 4139]
4098
{'jack': 4098, 'guido': 4127}
{'jack': 4098, 'guido': 4127, 'irv': 4127}
True
False


The [dict()](#) constructor builds dictionaries directly from sequences of key-value pairs:

In [47]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [48]:
{ x: x**2 for x in (2, 4, 6) }

{2: 4, 4: 16, 6: 36}

In [49]:
for x in 2, 4, 6:
  print(x)

2
4
6


In [50]:
t = 2, 4, 6
print(type(t), t)

for x in t:
  print(x)

<class 'tuple'> (2, 4, 6)
2
4
6


When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [51]:
dict(sape=4139, guido=4127, jack=4098)

{'guido': 4127, 'jack': 4098, 'sape': 4139}

## 5.6. Looping Techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the items() method.

In [55]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
  print('key:', k, ' value:', v)

key: gallahad  value: the pure
key: robin  value: the brave


When looping through a sequence, the position index and corresponding value can be retrieved at the same time using the [enumerate()](#) function.

In [56]:
for i, v in enumerate(['tic', 'tac', 'toe']):
  print(i, v)

0 tic
1 tac
2 toe


In [57]:
t = 2, 4, 6

for i, v in enumerate(t):
  print(i, v)

0 2
1 4
2 6


In [68]:
t = 'apple', 'banana', 'durian', 'cherry'

print(type(t), t)

for i, v in enumerate(t):
  print(i, v)

<class 'tuple'> ('apple', 'banana', 'durian', 'cherry')
0 apple
1 banana
2 durian
3 cherry


To loop over two or more sequences at the same time, the entries can be paired with the [zip()](#) function.

In [72]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']

for q, a in zip(questions, answers):
  print('What is your {0}? It is {1}.'.format(q, a))

What is your name? It is lancelot.
What is your quest? It is the holy grail.
What is your favorite color? It is blue.


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the [reversed()](#) function.

In [73]:
for i in reversed(range(1, 10, 2)):
  print(i)

9
7
5
3
1


To loop over a sequence in sorted order, use the [sorted()](#) function which returns a new sorted list while leaving the source unaltered.

In [74]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']

for f in sorted(set(basket)):
  print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [75]:
import math

raw_data = [56,2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
  if not math.isnan(value):
    filtered_data.append(value)
filtered_data

[56, 2, 51.7, 55.3, 52.5, 47.8]